### ISSUE TITLE
Can I apply this to any SDK, not just Alchemy?

### ISSUE THREAD

**Issue by vusa-rcardona** [net2devcrypto/Web3-Middleware-and-Backend-with-Alchemy#1]
Can I apply this to any SDK, not just Alchemy? I want to integrate to third party API's. Thanks!

**Comment by net2devcrypto** [comment]
Yes, as matter fact this is a standard backend implementation. This is not just for API's but basically any JS function execution.

**Comment by vusa-rcardona** [comment]
Thanks for your help!
